import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const API = process.env.REACT_APP_API_URL || 'http://localhost:3001';

export default function Reports({ token }) {
  const navigate = useNavigate();
  const [items, setItems] = useState([]);
  const [selected, setSelected] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState(null);
  const [aiResult, setAiResult] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({ title: '', report_type: '', period_start: '', period_end: '', generated_by: '', summary: '', metrics: '', status: 'draft' });

  const fetchItems = async () => { const res = await fetch(`${API}/api/reports`); setItems(await res.json()); setLoading(false); };
  useEffect(() => { fetchItems(); }, []);

  const handleSave = async () => {
    const method = editing ? 'PUT' : 'POST';
    const url = editing ? `${API}/api/reports/${editing.id}` : `${API}/api/reports`;
    await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
    setShowForm(false); setEditing(null);
    setForm({ title: '', report_type: '', period_start: '', period_end: '', generated_by: '', summary: '', metrics: '', status: 'draft' });
    fetchItems();
  };

  const handleDelete = async (id) => { if (!window.confirm('Delete this report?')) return; await fetch(`${API}/api/reports/${id}`, { method: 'DELETE' }); setSelected(null); fetchItems(); };

  const handleAI = async (id) => {
    setAiLoading(true); setAiResult(null);
    try { const res = await fetch(`${API}/api/reports/${id}/ai-insights`, { method: 'POST' }); const data = await res.json(); setAiResult(data.insights); }
    catch (err) { setAiResult('Error: ' + err.message); }
    setAiLoading(false);
  };

  const openEdit = (item) => {
    setEditing(item);
    setForm({ title: item.title, report_type: item.report_type, period_start: item.period_start ? item.period_start.split('T')[0] : '', period_end: item.period_end ? item.period_end.split('T')[0] : '', generated_by: item.generated_by, summary: item.summary, metrics: item.metrics, status: item.status });
    setShowForm(true); setSelected(null);
  };

  const openNew = () => { setEditing(null); setForm({ title: '', report_type: '', period_start: '', period_end: '', generated_by: '', summary: '', metrics: '', status: 'draft' }); setShowForm(true); };

  const formatAiContent = (text) => {
    if (!text) return '';
    return text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/^### (.*$)/gm, '<h3>$1</h3>').replace(/^## (.*$)/gm, '<h2>$1</h2>').replace(/^# (.*$)/gm, '<h1>$1</h1>').replace(/^- (.*$)/gm, '<div style="padding-left:16px">&#8226; $1</div>').replace(/^\d+\. (.*$)/gm, '<div style="padding-left:16px">$&</div>').replace(/\n/g, '<br/>');
  };

  if (loading) return <div className="loading">Loading reports...</div>;

  return (
    <div>
      <button className="btn-back" onClick={() => navigate('/')}>&#8592; Back to Dashboard</button>
      <div className="page-header">
        <h1>Analytics & Reports</h1>
        <div className="page-header-actions"><button className="btn-primary" onClick={openNew}>+ New Report</button></div>
      </div>

      <div className="data-table-container">
        <table className="data-table">
          <thead><tr><th>Title</th><th>Type</th><th>Period</th><th>Generated By</th><th>Status</th></tr></thead>
          <tbody>
            {items.map(item => (
              <tr key={item.id} onClick={() => { setSelected(item); setAiResult(null); }}>
                <td><strong>{item.title}</strong></td>
                <td>{item.report_type}</td>
                <td>{item.period_start ? new Date(item.period_start).toLocaleDateString() : ''} - {item.period_end ? new Date(item.period_end).toLocaleDateString() : ''}</td>
                <td>{item.generated_by}</td>
                <td><span className={`status-badge status-${item.status === 'published' ? 'verified' : 'pending'}`}>{item.status}</span></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {selected && (
        <div className="modal-overlay" onClick={() => setSelected(null)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header"><h2>Report Details</h2><button className="modal-close" onClick={() => setSelected(null)}>&times;</button></div>
            <div className="modal-body">
              <div className="detail-grid">
                <div className="detail-item"><div className="detail-label">Title</div><div className="detail-value">{selected.title}</div></div>
                <div className="detail-item"><div className="detail-label">Report Type</div><div className="detail-value">{selected.report_type}</div></div>
                <div className="detail-item"><div className="detail-label">Period Start</div><div className="detail-value">{selected.period_start ? new Date(selected.period_start).toLocaleDateString() : 'N/A'}</div></div>
                <div className="detail-item"><div className="detail-label">Period End</div><div className="detail-value">{selected.period_end ? new Date(selected.period_end).toLocaleDateString() : 'N/A'}</div></div>
                <div className="detail-item"><div className="detail-label">Generated By</div><div className="detail-value">{selected.generated_by}</div></div>
                <div className="detail-item"><div className="detail-label">Status</div><div className="detail-value"><span className={`status-badge status-${selected.status === 'published' ? 'verified' : 'pending'}`}>{selected.status}</span></div></div>
              </div>
              <div className="detail-item" style={{ marginTop: 16 }}><div className="detail-label">Summary</div><div className="detail-value">{selected.summary}</div></div>
              <div className="detail-item" style={{ marginTop: 12 }}><div className="detail-label">Key Metrics</div><div className="detail-value" style={{ fontFamily: 'monospace', fontSize: 13, background: '#f8f9fa', padding: 12, borderRadius: 8 }}>{selected.metrics}</div></div>
              <div style={{ marginTop: 20, display: 'flex', gap: 8 }}>
                <button className="btn-ai" onClick={() => handleAI(selected.id)}>&#9733; AI Generate Insights</button>
                <button className="btn-edit" onClick={() => openEdit(selected)}>Edit</button>
                <button className="btn-danger" onClick={() => handleDelete(selected.id)}>Delete</button>
              </div>
              {aiLoading && <div className="ai-loading"><div className="spinner"></div>AI generating insights...</div>}
              {aiResult && (
                <div className="ai-response">
                  <div className="ai-response-header"><span className="ai-badge">AI INSIGHTS</span></div>
                  <div className="ai-response-content" dangerouslySetInnerHTML={{ __html: formatAiContent(aiResult) }} />
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {showForm && (
        <div className="modal-overlay" onClick={() => setShowForm(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header"><h2>{editing ? 'Edit Report' : 'New Report'}</h2><button className="modal-close" onClick={() => setShowForm(false)}>&times;</button></div>
            <div className="modal-body">
              <div className="detail-grid">
                <div className="form-group"><label>Title</label><input value={form.title} onChange={e => setForm({...form, title: e.target.value})} /></div>
                <div className="form-group"><label>Report Type</label><select value={form.report_type} onChange={e => setForm({...form, report_type: e.target.value})}><option value="">Select...</option><option>Prescription Volume</option><option>Controlled Substance</option><option>Financial</option><option>Inventory</option><option>Staff Compliance</option><option>Pharmacovigilance</option><option>Quality</option><option>Regulatory</option><option>Operations</option><option>Clinical</option><option>Executive</option></select></div>
                <div className="form-group"><label>Period Start</label><input type="date" value={form.period_start} onChange={e => setForm({...form, period_start: e.target.value})} /></div>
                <div className="form-group"><label>Period End</label><input type="date" value={form.period_end} onChange={e => setForm({...form, period_end: e.target.value})} /></div>
                <div className="form-group"><label>Generated By</label><input value={form.generated_by} onChange={e => setForm({...form, generated_by: e.target.value})} /></div>
                <div className="form-group"><label>Status</label><select value={form.status} onChange={e => setForm({...form, status: e.target.value})}><option value="draft">Draft</option><option value="published">Published</option></select></div>
              </div>
              <div className="form-group"><label>Summary</label><textarea rows={3} value={form.summary} onChange={e => setForm({...form, summary: e.target.value})} /></div>
              <div className="form-group"><label>Key Metrics</label><textarea rows={2} value={form.metrics} onChange={e => setForm({...form, metrics: e.target.value})} /></div>
            </div>
            <div className="modal-footer"><button className="btn-secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="btn-primary" onClick={handleSave}>{editing ? 'Update' : 'Create'}</button></div>
          </div>
        </div>
      )}
    </div>
  );
}
